version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: erp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: erp_dev
      POSTGRES_USER: erp
      POSTGRES_PASSWORD: erp123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
